### ISSUE TITLE
Could not find a version while installing `backports.weakref`

### ISSUE THREAD

**Issue by andybergon** [pjdelport/backports.weakref#4]
If I try to install `backports.weakref` using `pip` on Python2.7 (`pip install backports.weakref`) I get the following error:
```
Collecting backports.weakref
  Could not find a version that satisfies the requirement backports.weakref (from versions: )
No matching distribution found for backports.weakref
```

Isn't the package anymore through Pip? I can still see the package on PyPi [here](https://pypi.python.org/pypi/backports.weakref).

**Comment by PiDelport** [comment]
I'm guessing this is because pip changed behaviour at some point to not install pre-release packages by default, unless given the `--pre` option.

Releasing 1.0 should avoid this; I'll get on that!
